# Generated by hand to match dashboard.models — run makemigrations only if models change.

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("english_name", models.CharField(max_length=64, unique=True)),
                ("chinese_name", models.CharField(max_length=64, unique=True)),
            ],
            options={"ordering": ["id"]},
        ),
        migrations.CreateModel(
            name="HouseholdIncome",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("year", models.IntegerField()),
                ("city_name", models.CharField(db_index=True, max_length=64)),
                ("county_code", models.CharField(blank=True, max_length=32)),
                ("avg_households", models.FloatField()),
                ("avg_employment", models.FloatField()),
                ("avg_income_earners", models.FloatField()),
                ("total", models.FloatField(help_text="Household income total, million TWD")),
            ],
        ),
        migrations.CreateModel(
            name="PopulationStat",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("year", models.IntegerField()),
                ("month", models.IntegerField()),
                ("city_name", models.CharField(db_index=True, max_length=64)),
                ("county_code", models.CharField(blank=True, max_length=32)),
                ("town_name", models.CharField(max_length=64)),
                ("town_code", models.CharField(max_length=32)),
                ("households", models.IntegerField()),
                ("population", models.IntegerField()),
                ("males", models.IntegerField()),
                ("females", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="StudentStatus",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("year", models.IntegerField()),
                ("city_name", models.CharField(db_index=True, max_length=64)),
                ("county_code", models.CharField(blank=True, max_length=32)),
                ("school_type", models.CharField(blank=True, max_length=64)),
                ("school_code", models.CharField(max_length=64)),
                ("school_name", models.CharField(max_length=255)),
                ("males", models.IntegerField()),
                ("females", models.IntegerField()),
                ("total", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="VehicleCount",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("year", models.IntegerField()),
                ("month", models.IntegerField()),
                ("city_name", models.CharField(db_index=True, max_length=64)),
                ("county_code", models.CharField(blank=True, max_length=32)),
                ("vehicle_type", models.CharField(max_length=64)),
                ("value", models.IntegerField()),
            ],
        ),
        migrations.AddConstraint(
            model_name="householdincome",
            constraint=models.UniqueConstraint(fields=("year", "city_name"), name="uniq_income_year_city"),
        ),
        migrations.AddConstraint(
            model_name="studentstatus",
            constraint=models.UniqueConstraint(
                fields=("year", "city_name", "school_code"),
                name="uniq_student_year_city_school",
            ),
        ),
        migrations.AddIndex(
            model_name="vehiclecount",
            index=models.Index(fields=["year", "month"], name="dashboard_v_year_month_idx"),
        ),
        migrations.AddConstraint(
            model_name="vehiclecount",
            constraint=models.UniqueConstraint(
                fields=("year", "month", "city_name", "vehicle_type"),
                name="uniq_vehicle_period_city_type",
            ),
        ),
        migrations.AddIndex(
            model_name="populationstat",
            index=models.Index(fields=["year", "month", "city_name"], name="dashboard_p_year_month_city_idx"),
        ),
        migrations.AddConstraint(
            model_name="populationstat",
            constraint=models.UniqueConstraint(
                fields=("year", "month", "town_code"),
                name="uniq_population_period_town",
            ),
        ),
    ]
